[View in Colaboratory](https://colab.research.google.com/github/jvargh81/Article/blob/master/tensorflow.ipynb)

In [0]:
import tensorflow as tf

In [2]:
x1 = tf.constant(4)
x2 = tf.constant(5)
y  = tf.add(x1,x2)

s1 = tf.Session()
print(s1.run(y))
s1.close

9


<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x7f521881ac18>>

In [3]:
x1 = tf.constant("Jerrin Joe ")
x2 = tf.constant("Varghese")
y  = tf.add(x1,x2)

with tf.Session() as s1:
  print(y.eval())

b'Jerrin Joe Varghese'


In [4]:
# place holder : Are not assigned any value, given value at execution time.
graph = tf.get_default_graph()

x = tf.placeholder(tf.float32)
y = tf.add(x,x)

with tf.Session() as s1:
  print(y.eval({x:[1,2,3,4,5,6,7,8,9,10]}))


print(graph.get_operations())

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[<tf.Operation 'Const' type=Const>, <tf.Operation 'Const_1' type=Const>, <tf.Operation 'Add' type=Add>, <tf.Operation 'Const_2' type=Const>, <tf.Operation 'Const_3' type=Const>, <tf.Operation 'Add_1' type=Add>, <tf.Operation 'Placeholder' type=Placeholder>, <tf.Operation 'Add_2' type=Add>]


In [5]:
graph = tf.get_default_graph()

x1 = tf.constant(4,name="x1")

print(graph.get_operations())

x2 = tf.constant(4,name="x2")

print(graph.get_operations())

y = tf.add(x1,x2,name="y")

print(graph.get_operations())

with tf.Session() as s1:
  y.eval()


[<tf.Operation 'Const' type=Const>, <tf.Operation 'Const_1' type=Const>, <tf.Operation 'Add' type=Add>, <tf.Operation 'Const_2' type=Const>, <tf.Operation 'Const_3' type=Const>, <tf.Operation 'Add_1' type=Add>, <tf.Operation 'Placeholder' type=Placeholder>, <tf.Operation 'Add_2' type=Add>, <tf.Operation 'x1' type=Const>]
[<tf.Operation 'Const' type=Const>, <tf.Operation 'Const_1' type=Const>, <tf.Operation 'Add' type=Add>, <tf.Operation 'Const_2' type=Const>, <tf.Operation 'Const_3' type=Const>, <tf.Operation 'Add_1' type=Add>, <tf.Operation 'Placeholder' type=Placeholder>, <tf.Operation 'Add_2' type=Add>, <tf.Operation 'x1' type=Const>, <tf.Operation 'x2' type=Const>]
[<tf.Operation 'Const' type=Const>, <tf.Operation 'Const_1' type=Const>, <tf.Operation 'Add' type=Add>, <tf.Operation 'Const_2' type=Const>, <tf.Operation 'Const_3' type=Const>, <tf.Operation 'Add_1' type=Add>, <tf.Operation 'Placeholder' type=Placeholder>, <tf.Operation 'Add_2' type=Add>, <tf.Operation 'x1' type=Const>,

In [6]:
# different types of initializer for the variables.
x1 = tf.Variable(4)
x2 = tf.Variable(5)
x1_init = x1.initializer
x2_init = x2.initializer
y  = tf.add(x1,x2)

var_init = tf.global_variables_initializer()

with tf.Session() as s1:
  #s1.run(x1.initializer)
  #s1.run(x2.initializer)
  #s1.run(x1_init)
  #s1.run(x2_init)
  s1.run(var_init)
  print(y.eval())

9


In [7]:
x = tf.placeholder(tf.int32)
s = tf.add(x,1)
t = tf.subtract(x,1)
z = tf.add(s,t)

with tf.Session() as s1:
  print(s.eval({x:[1,2,3,4,5,6]}))
  print(t.eval({x:[1,2,3,4,5,6]}))
  print(z.eval({x:[1,2,3,4,5,6]}))


[2 3 4 5 6 7]
[0 1 2 3 4 5]
[ 2  4  6  8 10 12]
